QT5_DEMOS += " \
cinematicexperience \
qt5everywheredemo \
qt5nmapcarousedemo \
qt5ledscreen \
qt5nmapper \
qtsmarthome \
quitbattery \
quitindicators \
"

QT5_PACKAGES = " \
qtbase \
qtbase-plugins \
qtbase-tools \
qtconnectivity \
qtconnectivity-qmlplugins \
qtcharts \
qtcharts-plugins \
qtcharts-qmlplugins \
qtdeclarative \
qtdeclarative-qmlplugins \
qtdeclarative-plugins \
qtimageformats \
qtimageformats-qmlplugins \
qtgraphicaleffects \
qtgraphicaleffects-qmlplugins \
qtimageformats \ 
qtmultimedia \
qtmultimedia-plugins \
qtmultimedia-qmlplugins \
qtquickcontrols \
qtquickcontrols2 \
qtquickcontrols2-qmlplugins \
qtserialport \
qtsvg \
qtsvg-plugins \
qtsystems \
qtsystems-qmlplugins \
qtscript \
qttools \
qtvirtualkeyboard \
"
