QT5_PACKAGES = " \
                qtbase \
                qtbase-plugins \
                qtbase-tools \
                qtconnectivity \
                qtconnectivity-qmlplugins \
                qtcharts \
                qtcharts-plugins \
                qtcharts-qmlplugins \
                qtdeclarative \
                qtdeclarative-qmlplugins \
                qtdeclarative-plugins \
                qtimageformats \
                qtimageformats-qmlplugins \
                qtgraphicaleffects \
                qtgraphicaleffects-qmlplugins \
                qtimageformats \ 
                qtmultimedia \
                qtmultimedia-plugins \
                qtmultimedia-qmlplugins \
                qtquickcontrols \
                qtquickcontrols2 \
                qtquickcontrols2-qmlplugins \
                qtserialport \
                qtsvg \
                qtsvg-plugins \
                qtsystems \
                qtsystems-qmlplugins \
                qtscript \
                qttools \
                qtvirtualkeyboard \
                "

GSTREAMER_PACKAGES = " \
                      gstreamer1.0-plugins-base \
                      gstreamer1.0-plugins-bad \
                      gstreamer1.0-plugins-good \
                      "